### ISSUE TITLE
Message error when logging out of site

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/ucb_admin_menus#29]
Whenever I log out of the site, I see the following message (and don't log out of the site): 

https://live-ucbdev-homepage.pantheonsite.io

![Screenshot 2024-05-21 at 9 27 25 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/5a3e5630-4280-48fd-a773-095d93c1aed4)

**Comment by jcsparks** [comment]
Talk with UI/UX team about this and FedAuth

**Comment by jcsparks** [comment]
Okay we're going to try to add some JS (probably in the admin theme) to look for the link with the href of `/user/logout` and rewrite that to a JS function that will attempt to delete the local site cookies and send them back to the homepage of the site.

**Comment by timurtripp** [comment]
This is turning into a kettle of worms type of problem. Two new observations:
- The logout redirect is coming from the simpleSAMLphp Authentication module. There is no way for me to debug this on my local system.
- A JavaScript solution to clear the cookies is likely inadequate. The user appears to be logged out but is actually not. Simply going back to the login page automatically authenticates again without prompting for a username and password. This will provide a false sense of being logged out which is not ideal from a security standpoint.

**Comment by timurtripp** [comment]
A possible solution to the latter problem may be to redirect to a page which instructs the user to close out of the browser if on a public computer. Simply redirecting to the home page fails to convey that they haven't been securely logged out, especially if the only time they logged in to something via FedAuth on that particular computer/browser was to edit something on the site.
