### ISSUE TITLE
Update Helpscout Beacon

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb_admin_menus#32]
Looks like the helpscout beacon is still pointed towards the Drupal 7 documentation.

Here's the code for the D10 documentation beacon:

`<script type="text/javascript">!function(e,t,n){function a(){var e=t.getElementsByTagName("script")[0],n=t.createElement("script");n.type="text/javascript",n.async=!0,n.src="https://beacon-v2.helpscout.net",e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],"complete"===t.readyState)return a();e.attachEvent?e.attachEvent("onload",a):e.addEventListener("load",a,!1)}(window,document,window.Beacon||function(){});</script>
<script type="text/javascript">window.Beacon('init', '7aeb6f1c-247c-4a83-b44f-4cee2784bb63')</script>`

**Comment by kevincrafts** [comment]
New beacon ID: 7aeb6f1c-247c-4a83-b44f-4cee2784bb63

**Comment by timurtripp** [comment]
@tirazel 

Drush command for setting the new id:

```sh
drush config:set ucb_admin_menus.configuration admin_helpscout_beacon_id 7aeb6f1c-247c-4a83-b44f-4cee2784bb63 -y
```

PHP command for setting the new id:

```php
\Drupal::configFactory()->getEditable('ucb_admin_menus.configuration')->set('admin_helpscout_beacon_id', '7aeb6f1c-247c-4a83-b44f-4cee2784bb63')->save();
```
